In [1]:
import tensorflow as tf
import numpy as np
from pandas import DataFrame as df

In [2]:
print(tf.__version__)

1.13.1


In [3]:
hello = tf.constant("Hello ")
world = tf.constant("World.")

In [4]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [5]:
hello.get_shape()

TensorShape([])

In [6]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [7]:
result

b'Hello World.'

In [8]:
a = tf.constant(5)
b = tf. constant(10)

In [9]:
c = a + b

In [10]:
c

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [11]:
with tf.Session() as sess:
    result = sess.run(c)

result

15

In [12]:
const = tf.constant(10)
ten_mat = tf.fill((4,4), 10)
zero_mat = tf.zeros((4,4))
one_mat = tf.ones((4,4))
randn_mat = tf.random_normal((4,4))
randu_mat = tf.random_uniform((4,4))

my_tensors = [const, ten_mat, zero_mat, one_mat, randn_mat, randu_mat]

with tf.Session() as sess:
    for tensor in my_tensors:
        print(tensor.eval(), "\n")

10 

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[ 1.3130556  -0.7188968   0.5478428  -0.21991397]
 [-0.9121856  -0.33883035 -0.14904931 -1.4991393 ]
 [-0.9954878   0.15442443  1.5725898  -0.23576404]
 [ 1.1507596  -0.26388955  0.51904726  0.46532038]] 

[[0.20771301 0.32412195 0.3101679  0.34855032]
 [0.8999548  0.37528372 0.54652    0.456743  ]
 [0.7071197  0.3979274  0.7014768  0.3927567 ]
 [0.05236268 0.32381117 0.5301111  0.8804189 ]] 



In [13]:
a = tf.constant([[1,2],
                 [3,4]])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [14]:
b = tf.constant([[10],
                 [100]])
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [15]:
result = tf.matmul(a, b)
with tf.Session() as sess:
    print(sess.run(result))

[[210]
 [430]]


In [16]:
graph = tf.get_default_graph()

In [17]:
graph

In [18]:
graph.collections

[]

In [19]:
graph.get_all_collection_keys()

[]

In [20]:
my_tensor = tf.random_uniform((4,4), 0, 1)
my_var = tf.Variable(initial_value=my_tensor)
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    result = sess.run(my_var)

Instructions for updating:
Colocations handled automatically by placer.


In [21]:
df(result)

0         1         2         3
0  0.040545  0.677158  0.427693  0.148594
1  0.055434  0.630373  0.031533  0.373211
2  0.859501  0.390211  0.946887  0.517992
3  0.212460  0.646939  0.678719  0.323120

In [22]:
np.random.seed(101)
tf.set_random_seed(101)

In [23]:
rand_a = np.random.uniform(0,100,(5,5))
df(rand_a)

0          1          2          3          4
0  51.639863  57.066759   2.847423  17.152166  68.527698
1  83.389686  30.696622  89.361308  72.154386  18.993895
2  55.422759  35.213195  18.189240  78.560176  96.548322
3  23.235366   8.356143  60.354842  72.899276  27.623883
4  68.530633  51.786747   4.848454  13.786924  18.696743

In [24]:
rand_b = np.random.uniform(0,100,(5,1))

df(rand_b)

0
0  99.431790
1  52.066540
2  57.878954
3  73.481906
4  54.196177

In [25]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

add_op = a + b
mul_op = tf.matmul(a, b)

In [26]:
with tf.Session() as sess:
    add_result = sess.run(add_op, feed_dict={a:rand_a, b:rand_b})
    mul_result = sess.run(mul_op, feed_dict={a:rand_a, b:rand_b})

In [27]:
df(add_result)

0           1           2           3           4
0  151.071655  156.498550  102.279213  116.583961  167.959488
1  135.456223   82.763161  141.427841  124.220932   71.060432
2  113.301712   93.092148   76.068192  136.439117  154.427277
3   96.717270   81.838043  133.836746  146.381180  101.105789
4  122.726807  105.982925   59.044632   67.983101   72.892921

In [28]:
df(mul_result)

0
0  13245.032227
1  21393.429688
2  19402.289062
3  13092.570312
4  11817.485352

In [29]:
rand_a.dot(rand_b)

array([[13245.03158833],
       [21393.42999295],
       [19402.28903044],
       [13092.57119768],
       [11817.48508187]])